/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkoutDetailsRouteImport } from './routes/workout-details'
import { Route as QuestionnaireRouteImport } from './routes/questionnaire'
import { Route as MealDetailsRouteImport } from './routes/meal-details'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'

const WorkoutDetailsRoute = WorkoutDetailsRouteImport.update({
  id: '/workout-details',
  path: '/workout-details',
  getParentRoute: () => rootRouteImport,
} as any)
const QuestionnaireRoute = QuestionnaireRouteImport.update({
  id: '/questionnaire',
  path: '/questionnaire',
  getParentRoute: () => rootRouteImport,
} as any)
const MealDetailsRoute = MealDetailsRouteImport.update({
  id: '/meal-details',
  path: '/meal-details',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/meal-details': typeof MealDetailsRoute
  '/questionnaire': typeof QuestionnaireRoute
  '/workout-details': typeof WorkoutDetailsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/meal-details': typeof MealDetailsRoute
  '/questionnaire': typeof QuestionnaireRoute
  '/workout-details': typeof WorkoutDetailsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/meal-details': typeof MealDetailsRoute
  '/questionnaire': typeof QuestionnaireRoute
  '/workout-details': typeof WorkoutDetailsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/meal-details'
    | '/questionnaire'
    | '/workout-details'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/login'
    | '/meal-details'
    | '/questionnaire'
    | '/workout-details'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/meal-details'
    | '/questionnaire'
    | '/workout-details'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  MealDetailsRoute: typeof MealDetailsRoute
  QuestionnaireRoute: typeof QuestionnaireRoute
  WorkoutDetailsRoute: typeof WorkoutDetailsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workout-details': {
      id: '/workout-details'
      path: '/workout-details'
      fullPath: '/workout-details'
      preLoaderRoute: typeof WorkoutDetailsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/questionnaire': {
      id: '/questionnaire'
      path: '/questionnaire'
      fullPath: '/questionnaire'
      preLoaderRoute: typeof QuestionnaireRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meal-details': {
      id: '/meal-details'
      path: '/meal-details'
      fullPath: '/meal-details'
      preLoaderRoute: typeof MealDetailsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  MealDetailsRoute: MealDetailsRoute,
  QuestionnaireRoute: QuestionnaireRoute,
  WorkoutDetailsRoute: WorkoutDetailsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
